[package]
name = "string_processing"
version = "0.1.0"
edition = "2024"

[dependencies]
cyclic-poly-23 = "0.4.0"
itertools = "0.14.0"
pyo3 = {version = "0.25.0", features = ["extension-module"] }

[lib]
name = "string_processing"
crate-type = ["cdylib"]
