#
#
#name: Build Rust Python wheels for all platforms. v1
#
#on:
#  push:
#    branches:
#      - master
#
#env:
#  PACKAGE_NAME: string_processing
#
#
#jobs:
#  build-wheels:
#    name: Build wheels (${{ matrix.os }}, Python ${{ matrix.python-version }})
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest] #, windows-latest]
#        python-version: ["3.10"] #, "3.11", "3.12"]
#      fail-fast: true
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v5
#      with:
#        python-version: ${{ matrix.python-version }}
#
#    - name: Install Rust
#      uses: dtolnay/rust-toolchain@stable
#      with:
#        toolchain: stable
#        components: rustfmt, clippy
#
#    - name: Install maturin
#      run: pip install maturin==1.4.0
#
#    - name: Build wheels
#      run: maturin build --release --strip --interpreter python --out wheels/
#      env:
#        MATURIN_PYPI_MANYLINUX: auto
#
#    - name: Upload wheels
#      uses: actions/upload-artifact@v4
#      with:
#        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
#        path: wheels/*.whl
#        retention-days: 5
#
#  package:
#    needs: build-wheels
#    runs-on: ubuntu-latest
#    permissions: write-all
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Download all built wheels
#        uses: actions/download-artifact@v4
#        with:
#          path: simple
#
#      - name: Move wheels to PyPI-style structure
#        run: |
#          mkdir -p simple/string_processing/
#          find simple -name '*.whl' -exec cp {} simple/string_processing/ \;
#
#      - name: Generate package index
#        run: |
#          cd simple/string_processing/
#          echo "<html><body>" > index.html
#          for whl in *.whl; do
#            echo "<a href=\"$whl\">$whl</a><br>" >> index.html
#          done
#          echo "</body></html>" >> index.html
#          cd ../
#          echo "<html><body><a href=\"string_processing/\">string_processing</a><br></body></html>" > index.html
#
#      - name: Commit and push static index
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: "Update GitHub Pages package index"
#          branch: master
