name: Release python package to PyPi


on:
  push:
    branches:
      - pypi_release

jobs:
  build-wheels:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/build_wheels.yml

  upload-to-pypi:
    needs: build-wheels
    name: Upload pre-built wheels to pypi
    runs-on: ubuntu-latest

    steps:
#      - name: Set up python
#        uses: actions/setup-python@v5
#      - name: Download built wheels
#          uses: actions/download-artifact@v4
#          with:
#            name: built-wheels
#            path: dist
#
#      - name: List wheels
#          run: ls -l dist
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: List wheels
        run: ls -l dist

      - name: Install twine
        run: pip install twine

      - name: Echo something weird
        run: echo "HEeeelloooo"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__                   # Always "__token__" for token authentication
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # Add this secret in your GitHub repo!
        run: twine upload dist/*